model = "gpt-5-codex"
model_reasoning_effort = "medium"
model_reasoning_summary = "detailed"
model_verbosity = "high"
file_opener = "none"
show_raw_agent_reasoning = true
sandbox_mode = "danger-full-access"
approval_policy = "never"

[features]
web_search_request = true

[shell_environment_policy]
inherit = "all"
ignore_default_excludes = true

[mcp_servers.deepwiki]
command = "npx"
args = ["mcp-remote", "https://mcp.deepwiki.com/mcp"]
